name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches: [varunsharma/eng-1268-hackathonopen-research-day-v1-ve]
  pull_request: # Optional: Add builds on pull requests

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Checkout code from your repository

      - name: Login to AWS ECR
        uses: aws-actions/aws-ecr-login@v2 # Login to ECR with AWS credentials
        with:
          aws-region: us-east-1 # Replace with your AWS region
          registry: 099440147872.dkr.ecr.us-east-1.amazonaws.com/stable-audio-open # Replace with your ECR registry URI
          registry: ${{ secrets.AWS_ECR_REGISTRY_URI }}
      - name: Build the Docker Image
        run: |
          docker build -t stable-audio-open .

      - name: Tag the Docker Image
        run: |
          docker tag stable-audio-open:latest 099440147872.dkr.ecr.us-east-1.amazonaws.com/stable-audio-open:latest

      - name: Push the Docker Image to ECR
        run: |
          docker push 099440147872.dkr.ecr.us-east-1.amazonaws.com/stable-audio-open:latest  # Push the built image
